export const filters = ["All", "About", "Projects", "Media"];

export const layouts = {
  all: {
    lg: [
      {
        i: "bio",
        x: 0,
        y: 0,
        w: 2,
        h: 1,
        isResizable: false,
      },
      {
        i: "map",
        x: 2,
        y: 0,
        w: 1,
        h: 1,
        isResizable: false,
      },
      {
        i: "recroot",
        x: 3,
        y: 0,
        w: 1,
        h: 2,
        isResizable: false,
      },
      {
        i: "spotify",
        x: 0,
        y: 1,
        w: 1,
        h: 1,
        isResizable: false,
      },
      {
        i: "twitter",
        x: 1,
        y: 0,
        w: 1,
        h: 1,
        isResizable: false,
      },
      {
        i: "vouch-for",
        x: 2,
        y: 1,
        w: 1,
        h: 2,
        isResizable: false,
      },
      {
        i: "blog-excerpt",
        x: 0,
        y: 2,
        w: 2,
        h: 1,
        isResizable: false,
      },
      {
        i: "wrap",
        x: 0,
        y: 3,
        w: 2,
        h: 1,
        isResizable: false,
      },
      {
        i: "mode-toggle",
        x: 3,
        y: 2,
        w: 1,
        h: 1,
        isResizable: false,
      },
      {
        i: "newsletter",
        x: 2,
        y: 3,
        w: 2,
        h: 1,
        isResizable: false,
      },
    ],
    md: [
      {
        i: "bio",
        x: 0,
        y: 0,
        w: 2,
        h: 2,
        isResizable: false,
      },
      {
        i: "map",
        x: 2,
        y: 0,
        w: 1,
        h: 1,
        isResizable: false,
      },
      {
        i: "recroot",
        x: 3,
        y: 0,
        w: 1,
        h: 2,
        isResizable: false,
      },
      {
        i: "spotify",
        x: 0,
        y: 2,
        w: 2,
        h: 1,
        isResizable: false,
      },
      {
        i: "twitter",
        x: 1,
        y: 5,
        w: 1,
        h: 1,
        isResizable: false,
      },
      {
        i: "vouch-for",
        x: 2,
        y: 1,
        w: 1,
        h: 2,
        isResizable: false,
      },
      {
        i: "blog-excerpt",
        x: 0,
        y: 3,
        w: 2,
        h: 2,
        isResizable: false,
      },
      {
        i: "wrap",
        x: 2,
        y: 3,
        w: 2,
        h: 1,
        isResizable: false,
      },
      {
        i: "mode-toggle",
        x: 3,
        y: 2,
        w: 1,
        h: 1,
        isResizable: false,
      },
      {
        i: "newsletter",
        x: 2,
        y: 4,
        w: 2,
        h: 2,
        isResizable: false,
      },
    ],
    sm: [
      {
        i: "bio",
        x: 0,
        y: 0,
        w: 2,
        h: 2,
        isResizable: false,
      },
      {
        i: "map",
        x: 0,
        y: 2,
        w: 2,
        h: 1,
        isResizable: false,
      },
      {
        i: "recroot",
        x: 1,
        y: 3,
        w: 1,
        h: 2,
        isResizable: false,
      },
      {
        i: "spotify",
        x: 0,
        y: 6,
        w: 2,
        h: 2,
        isResizable: false,
      },
      {
        i: "twitter",
        x: 0,
        y: 3,
        w: 1,
        h: 1,
        isResizable: false,
      },
      {
        i: "vouch-for",
        x: 0,
        y: 4,
        w: 1,
        h: 2,
        isResizable: false,
      },
      {
        i: "blog-excerpt",
        x: 0,
        y: 8,
        w: 2,
        h: 2,
        isResizable: false,
      },
      {
        i: "wrap",
        x: 0,
        y: 10,
        w: 2,
        h: 1,
        isResizable: false,
      },
      {
        i: "mode-toggle",
        x: 1,
        y: 5,
        w: 1,
        h: 1,
        isResizable: false,
      },
      {
        i: "newsletter",
        x: 0,
        y: 11,
        w: 2,
        h: 2,
        isResizable: false,
      },
    ],
  },
  about: {
    lg: [
      {
        i: "bio",
        x: 0,
        y: 0,
        w: 2,
        h: 1,
        isResizable: false,
      },
      {
        i: "map",
        x: 2,
        y: 0,
        w: 1,
        h: 1,
        isResizable: false,
      },
      {
        i: "recroot",
        x: 3,
        y: 1,
        w: 1,
        h: 2,
        isResizable: false,
      },
      {
        i: "spotify",
        x: 0,
        y: 1,
        w: 1,
        h: 1,
        isResizable: false,
      },
      {
        i: "twitter",
        x: 3,
        y: 0,
        w: 1,
        h: 1,
        isResizable: false,
      },
      {
        i: "vouch-for",
        x: 2,
        y: 1,
        w: 1,
        h: 2,
        isResizable: false,
      },
      {
        i: "blog-excerpt",
        x: 0,
        y: 2,
        w: 2,
        h: 1,
        isResizable: false,
      },
      {
        i: "wrap",
        x: 0,
        y: 3,
        w: 2,
        h: 1,
        isResizable: false,
      },
      {
        i: "mode-toggle",
        x: 1,
        y: 1,
        w: 1,
        h: 1,
        isResizable: false,
      },
      {
        i: "newsletter",
        x: 2,
        y: 3,
        w: 2,
        h: 1,
        isResizable: false,
      },
    ],
    md: [
      {
        i: "bio",
        x: 0,
        y: 0,
        w: 2,
        h: 2,
        isResizable: false,
      },
      {
        i: "map",
        x: 2,
        y: 0,
        w: 1,
        h: 1,
        isResizable: false,
      },
      {
        i: "recroot",
        x: 3,
        y: 1,
        w: 1,
        h: 2,
        isResizable: false,
      },
      {
        i: "spotify",
        x: 0,
        y: 2,
        w: 2,
        h: 1,
        isResizable: false,
      },
      {
        i: "twitter",
        x: 3,
        y: 0,
        w: 1,
        h: 1,
        isResizable: false,
      },
      {
        i: "vouch-for",
        x: 2,
        y: 1,
        w: 1,
        h: 2,
        isResizable: false,
      },
      {
        i: "blog-excerpt",
        x: 0,
        y: 3,
        w: 2,
        h: 2,
        isResizable: false,
      },
      {
        i: "wrap",
        x: 2,
        y: 3,
        w: 2,
        h: 1,
        isResizable: false,
      },
      {
        i: "mode-toggle",
        x: 1,
        y: 5,
        w: 1,
        h: 1,
        isResizable: false,
      },
      {
        i: "newsletter",
        x: 2,
        y: 4,
        w: 2,
        h: 2,
        isResizable: false,
      },
    ],
    sm: [
      {
        i: "bio",
        x: 0,
        y: 1,
        w: 2,
        h: 2,
        isResizable: false,
      },
      {
        i: "map",
        x: 0,
        y: 0,
        w: 2,
        h: 1,
        isResizable: false,
      },
      {
        i: "recroot",
        x: 1,
        y: 3,
        w: 1,
        h: 2,
        isResizable: false,
      },
      {
        i: "spotify",
        x: 0,
        y: 6,
        w: 2,
        h: 2,
        isResizable: false,
      },
      {
        i: "twitter",
        x: 0,
        y: 3,
        w: 1,
        h: 1,
        isResizable: false,
      },
      {
        i: "vouch-for",
        x: 0,
        y: 4,
        w: 1,
        h: 2,
        isResizable: false,
      },
      {
        i: "blog-excerpt",
        x: 0,
        y: 8,
        w: 2,
        h: 2,
        isResizable: false,
      },
      {
        i: "wrap",
        x: 0,
        y: 10,
        w: 2,
        h: 1,
        isResizable: false,
      },
      {
        i: "mode-toggle",
        x: 1,
        y: 5,
        w: 1,
        h: 1,
        isResizable: false,
      },
      {
        i: "newsletter",
        x: 0,
        y: 11,
        w: 2,
        h: 2,
        isResizable: false,
      },
    ],
  },
  projects: {
    lg: [
      {
        i: "bio",
        x: 0,
        y: 1,
        w: 2,
        h: 1,
        isResizable: false,
      },
      {
        i: "map",
        x: 2,
        y: 2,
        w: 1,
        h: 1,
        isResizable: false,
      },
      {
        i: "recroot",
        x: 3,
        y: 0,
        w: 1,
        h: 2,
        isResizable: false,
      },
      {
        i: "spotify",
        x: 0,
        y: 1,
        w: 1,
        h: 1,
        isResizable: false,
      },
      {
        i: "twitter",
        x: 3,
        y: 0,
        w: 1,
        h: 1,
        isResizable: false,
      },
      {
        i: "vouch-for",
        x: 2,
        y: 0,
        w: 1,
        h: 2,
        isResizable: false,
      },
      {
        i: "blog-excerpt",
        x: 0,
        y: 2,
        w: 2,
        h: 1,
        isResizable: false,
      },
      {
        i: "wrap",
        x: 0,
        y: 0,
        w: 2,
        h: 1,
        isResizable: false,
      },
      {
        i: "mode-toggle",
        x: 1,
        y: 1,
        w: 1,
        h: 1,
        isResizable: false,
      },
      {
        i: "newsletter",
        x: 2,
        y: 3,
        w: 2,
        h: 1,
        isResizable: false,
      },
    ],
    md: [
      {
        i: "bio",
        x: 0,
        y: 1,
        w: 2,
        h: 2,
        isResizable: false,
      },
      {
        i: "map",
        x: 2,
        y: 2,
        w: 1,
        h: 1,
        isResizable: false,
      },
      {
        i: "recroot",
        x: 3,
        y: 0,
        w: 1,
        h: 2,
        isResizable: false,
      },
      {
        i: "spotify",
        x: 0,
        y: 2,
        w: 2,
        h: 1,
        isResizable: false,
      },
      {
        i: "twitter",
        x: 3,
        y: 0,
        w: 1,
        h: 1,
        isResizable: false,
      },
      {
        i: "vouch-for",
        x: 2,
        y: 0,
        w: 1,
        h: 2,
        isResizable: false,
      },
      {
        i: "blog-excerpt",
        x: 0,
        y: 3,
        w: 2,
        h: 2,
        isResizable: false,
      },
      {
        i: "wrap",
        x: 0,
        y: 0,
        w: 2,
        h: 1,
        isResizable: false,
      },
      {
        i: "mode-toggle",
        x: 2,
        y: 5,
        w: 1,
        h: 1,
        isResizable: false,
      },
      {
        i: "newsletter",
        x: 2,
        y: 4,
        w: 2,
        h: 2,
        isResizable: false,
      },
    ],
    sm: [
      {
        i: "bio",
        x: 0,
        y: 3,
        w: 2,
        h: 2,
        isResizable: false,
      },
      {
        i: "map",
        x: 0,
        y: 2,
        w: 2,
        h: 1,
        isResizable: false,
      },
      {
        i: "recroot",
        x: 1,
        y: 0,
        w: 1,
        h: 2,
        isResizable: false,
      },
      {
        i: "spotify",
        x: 0,
        y: 6,
        w: 2,
        h: 2,
        isResizable: false,
      },
      {
        i: "twitter",
        x: 0,
        y: 3,
        w: 1,
        h: 1,
        isResizable: false,
      },
      {
        i: "vouch-for",
        x: 0,
        y: 0,
        w: 1,
        h: 2,
        isResizable: false,
      },
      {
        i: "blog-excerpt",
        x: 0,
        y: 8,
        w: 2,
        h: 2,
        isResizable: false,
      },
      {
        i: "wrap",
        x: 0,
        y: 1,
        w: 2,
        h: 1,
        isResizable: false,
      },
      {
        i: "mode-toggle",
        x: 1,
        y: 5,
        w: 1,
        h: 1,
        isResizable: false,
      },
      {
        i: "newsletter",
        x: 0,
        y: 11,
        w: 2,
        h: 2,
        isResizable: false,
      },
    ],
  },
  media: {
    lg: [
      {
        i: "bio",
        x: 0,
        y: 3,
        w: 2,
        h: 1,
        isResizable: false,
      },
      {
        i: "map",
        x: 1,
        y: 1,
        w: 1,
        h: 1,
        isResizable: false,
      },
      {
        i: "recroot",
        x: 3,
        y: 0,
        w: 1,
        h: 2,
        isResizable: false,
      },
      {
        i: "spotify",
        x: 0,
        y: 1,
        w: 1,
        h: 1,
        isResizable: false,
      },
      {
        i: "twitter",
        x: 3,
        y: 1,
        w: 1,
        h: 1,
        isResizable: false,
      },
      {
        i: "vouch-for",
        x: 2,
        y: 1,
        w: 1,
        h: 2,
        isResizable: false,
      },
      {
        i: "blog-excerpt",
        x: 0,
        y: 0,
        w: 2,
        h: 1,
        isResizable: false,
      },
      {
        i: "wrap",
        x: 0,
        y: 2,
        w: 2,
        h: 1,
        isResizable: false,
      },
      {
        i: "mode-toggle",
        x: 2,
        y: 3,
        w: 1,
        h: 1,
        isResizable: false,
      },
      {
        i: "newsletter",
        x: 2,
        y: 0,
        w: 2,
        h: 1,
        isResizable: false,
      },
    ],
    md: [
      {
        i: "bio",
        x: 0,
        y: 3,
        w: 2,
        h: 2,
        isResizable: false,
      },
      {
        i: "map",
        x: 2,
        y: 2,
        w: 1,
        h: 1,
        isResizable: false,
      },
      {
        i: "recroot",
        x: 3,
        y: 0,
        w: 1,
        h: 2,
        isResizable: false,
      },
      {
        i: "spotify",
        x: 0,
        y: 0,
        w: 2,
        h: 1,
        isResizable: false,
      },
      {
        i: "twitter",
        x: 3,
        y: 0,
        w: 1,
        h: 1,
        isResizable: false,
      },
      {
        i: "vouch-for",
        x: 2,
        y: 2,
        w: 1,
        h: 2,
        isResizable: false,
      },
      {
        i: "blog-excerpt",
        x: 0,
        y: 1,
        w: 2,
        h: 2,
        isResizable: false,
      },
      {
        i: "wrap",
        x: 0,
        y: 5,
        w: 2,
        h: 1,
        isResizable: false,
      },
      {
        i: "mode-toggle",
        x: 2,
        y: 5,
        w: 1,
        h: 1,
        isResizable: false,
      },
      {
        i: "newsletter",
        x: 2,
        y: 0,
        w: 2,
        h: 2,
        isResizable: false,
      },
    ],
    sm: [
      {
        i: "bio",
        x: 0,
        y: 10,
        w: 2,
        h: 2,
        isResizable: false,
      },
      {
        i: "map",
        x: 0,
        y: 9,
        w: 2,
        h: 1,
        isResizable: false,
      },
      {
        i: "recroot",
        x: 1,
        y: 6,
        w: 1,
        h: 2,
        isResizable: false,
      },
      {
        i: "spotify",
        x: 0,
        y: 0,
        w: 2,
        h: 2,
        isResizable: false,
      },
      {
        i: "twitter",
        x: 0,
        y: 12,
        w: 1,
        h: 1,
        isResizable: false,
      },
      {
        i: "vouch-for",
        x: 0,
        y: 6,
        w: 1,
        h: 2,
        isResizable: false,
      },
      {
        i: "blog-excerpt",
        x: 0,
        y: 2,
        w: 2,
        h: 2,
        isResizable: false,
      },
      {
        i: "wrap",
        x: 0,
        y: 8,
        w: 2,
        h: 1,
        isResizable: false,
      },
      {
        i: "mode-toggle",
        x: 1,
        y: 12,
        w: 1,
        h: 1,
        isResizable: false,
      },
      {
        i: "newsletter",
        x: 0,
        y: 4,
        w: 2,
        h: 2,
        isResizable: false,
      },
    ],
  },
};

export const heights: { [key: string]: number } = {
  lg: 280,
  md: 180,
  sm: 164,
  xs: 136,
};

export const memojis = ["images/memoji-1.png", "images/memoji-2.png"];
